baseurl = "https://www.koverholt.com/"
languageCode = "en-us"
title = "Kristopher Overholt"
theme = "hugo-lithium"
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
    name = "Blog"
    url = "https://cloud.koverholt.com"
    weight = 10
[[menu.main]]
    name = "Apps"
    url = "/apps/"
    weight = 20
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/koverholt"
    weight = 30
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/koverholt"
    weight = 40

[params]
    description = "Kristopher Overholt"
    favicon = "images/favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 421
    height = 120
    alt = "Kristopher Overholt"
