baseurl = "https://www.koverholt.com/"
languageCode = "en-us"
title = "Kristopher Overholt"
theme = "hugo-lithium"
googleAnalytics = ""
disableKinds = [“taxonomy”, “taxonomyTerm”]

[[menu.main]]
    name = "Apps"
    url = "/apps/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/koverholt"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/koverholt"

[params]
    description = "Kristopher Overholt"

    [params.logo]
    url = "logo.png"
    width = 421
    height = 120
    alt = "Kristopher Overholt"
